name: Release/transpile Node

on:
  push:
    branches: [main]
  release:
    branches: [main]
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # Some of this is from https://github.com/discordeno/discordeno/blob/main/.github/workflows/release.yml
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Deno Lint
        run: deno lint
        
      - name: Build npm folder
        run: deno run -A --unstable ./scripts/dnt.ts
        
      - name: Remove node_modules
        run: rm -rf npm/node_modules

      # Branch can be used for dev builds
      - name: Push to Node branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: node
          FOLDER: npm
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"